services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: charmander-api
    restart: always
    ports:
      - "4231:4231"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=payments
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: charmander-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
